"""Deterministic, read-only Node-RED flow exporter."""

from __future__ import annotations

import hashlib
from typing import Any, Mapping

from .exporters import (
    Artifact,
    ExportResult,
    Finding,
    block_area,
    block_function_code,
    block_id,
    block_quantity,
    block_route_id,
    block_start,
    block_unit_id,
    blocks_from_plan,
    canonical_map_hash,
    env_prefix_for_route,
    has_errors,
    held_result,
    normalize_mode,
    point_byte_order,
    point_datatype,
    point_id,
    point_name,
    point_protocol_offset,
    point_word_count,
    points_for_block,
    preflight_common,
    read_plan_hash,
    safe_slug,
    stable_json,
    target_manifest,
)


ADAPTER_VERSION = "2.0.0"
TARGET = "node-red"
_PROBE_BYTE_ORDER_LAYOUTS = ("ABCD", "BADC", "CDAB", "DCBA")
_PROBE_32_BIT_INTERPRETATIONS = ("uint32", "int32", "float32")


def export_node_red(
    canonical_map: Mapping[str, Any],
    read_plan: Mapping[str, Any],
    *,
    mode: str = "final",
    options: Mapping[str, Any] | None = None,
) -> ExportResult:
    """Generate a disabled Node-RED flow from one canonical read plan.

    Each flow uses one manual ``inject`` node and a response-driven sequencer.
    The sequencer shares one ``modbus-flex-getter`` per route and never has
    more than one request in flight. The flow contains no scheduled polling or
    write node in either mode. Final flows decode only confirmed layouts.
    """

    mode = normalize_mode(mode)
    options = dict(options or {})
    findings = list(preflight_common(canonical_map, read_plan, mode=mode))
    if has_errors(findings):
        return held_result(
            TARGET,
            canonical_map,
            read_plan,
            mode=mode,
            adapter_version=ADAPTER_VERSION,
            findings=findings,
        )

    map_digest = canonical_map_hash(canonical_map)
    plan_digest = read_plan_hash(read_plan)
    seed = f"{TARGET}:{map_digest}:{plan_digest}:{mode}"
    flow_id = _node_id(seed, "tab")
    flow_label = str(
        options.get("flow_label", f"Modbus Tool Pack - {mode.title()}")
    ).strip() or f"Modbus Tool Pack - {mode.title()}"

    blocks = sorted(
        enumerate(blocks_from_plan(read_plan)),
        key=lambda item: block_id(item[1], item[0]),
    )
    routes = sorted({block_route_id(block) for _, block in blocks})
    multiple_routes = len(routes) > 1
    route_env = {
        route: env_prefix_for_route(route, multiple_routes=multiple_routes)
        for route in routes
    }
    routes_by_prefix: dict[str, list[str]] = {}
    for route, prefix in route_env.items():
        routes_by_prefix.setdefault(prefix, []).append(route)
    for prefix, matching_routes in sorted(routes_by_prefix.items()):
        if len(matching_routes) > 1:
            findings.append(
                Finding(
                    "error",
                    "NODE_RED_ENV_PREFIX_COLLISION",
                    f"Routes {matching_routes!r} collapse to the same environment prefix {prefix!r}.",
                    "routes",
                )
            )
    if has_errors(findings):
        return held_result(
            TARGET,
            canonical_map,
            read_plan,
            mode=mode,
            adapter_version=ADAPTER_VERSION,
            findings=findings,
        )

    nodes: list[dict[str, Any]] = [
        {
            "id": flow_id,
            "type": "tab",
            "label": flow_label,
            "disabled": True,
            "info": (
                "Generated by modbus-skills. This flow is disabled by default. "
                "Review the endpoint, unit IDs, and ranges before enabling it."
            ),
            "env": [],
        }
    ]

    clients: dict[str, str] = {}
    for route in routes:
        prefix = route_env[route]
        client_id = _node_id(seed, f"client:{route}")
        clients[route] = client_id
        nodes.append(
            {
                "id": client_id,
                "type": "modbus-client",
                "name": f"Modbus route: {route}",
                "clienttype": "tcp",
                "bufferCommands": True,
                "stateLogEnabled": False,
                "queueLogEnabled": False,
                "failureLogEnabled": True,
                "tcpHost": "${" + prefix + "_HOST}",
                "tcpPort": "${" + prefix + "_PORT}",
                "tcpType": "DEFAULT",
                "serialPort": "",
                "serialType": "RTU-BUFFERD",
                "serialBaudrate": "9600",
                "serialDatabits": "8",
                "serialStopbits": "1",
                "serialParity": "none",
                "serialConnectionDelay": "100",
                "unit_id": 1,
                "commandDelay": 1,
                "clientTimeout": 1000,
                "reconnectOnTimeout": True,
                "reconnectTimeout": 2000,
                "parallelUnitIdsAllowed": False,
                "showWarnings": True,
                "showLogs": False,
            }
        )

    block_specs: list[dict[str, Any]] = []
    for order_index, (source_index, block) in enumerate(blocks):
        identifier = block_id(block, source_index)
        route = block_route_id(block)
        area = block_area(block)
        unit = block_unit_id(block)
        start = block_start(block)
        quantity = block_quantity(block)
        function_code = block_function_code(block)
        assert area is not None
        assert unit is not None
        assert start is not None
        assert quantity is not None
        assert function_code is not None

        specs = []
        for point_index, point in enumerate(
            points_for_block(canonical_map, block, source_index)
        ):
            identifier_for_point = point_id(point, point_index) or f"point-{point_index + 1}"
            point_start = point_protocol_offset(point)
            specs.append(
                {
                    "point_id": identifier_for_point,
                    "name": point_name(point, identifier_for_point),
                    "relative_offset": (point_start - start) if point_start is not None else None,
                    "word_count": point_word_count(point),
                    "datatype": point_datatype(point),
                    "byte_order": point_byte_order(point),
                    "scale": point.get("scale"),
                    "offset": point.get("engineering_offset", point.get("offset")),
                    "engineering_unit": point.get(
                        "engineering_unit", point.get("unit")
                    ),
                }
            )

        block_specs.append(
            {
                "block_id": identifier,
                "route_id": route,
                "route_index": routes.index(route),
                "unit_id": unit,
                "area": area,
                "function_code": function_code,
                "start_offset": start,
                "quantity": quantity,
                "mode": mode,
                "point_specs": specs,
            }
        )

    inject_id = _node_id(seed, "inject:plan")
    sequencer_id = _node_id(seed, "sequencer")
    response_gate_id = _node_id(seed, "response-gate")
    decode_id = _node_id(seed, "derive")
    capture_id = _node_id(seed, "capture")
    capture_file_id = _node_id(seed, "capture-file")
    watchdog_id = _node_id(seed, "watchdog")
    watchdog_reset_id = _node_id(seed, "watchdog-reset")
    error_debug_id = _node_id(seed, "errors")
    watchdog_debug_id = _node_id(seed, "watchdog-debug")
    plan_status_debug_id = _node_id(seed, "plan-status")
    read_ids = [_node_id(seed, f"read:{route}") for route in routes]

    nodes.extend(
        [
            {
                "id": inject_id,
                "type": "inject",
                "z": flow_id,
                "name": "Run bounded read plan",
                "props": [{"p": "payload"}],
                "repeat": "",
                "crontab": "",
                "once": False,
                "onceDelay": 0.1,
                "payload": stable_json({"action": "start"}, pretty=False),
                "payloadType": "json",
                "x": 170,
                "y": 150,
                "wires": [[sequencer_id]],
            },
            {
                "id": sequencer_id,
                "type": "function",
                "z": flow_id,
                "name": "Run bounded read plan",
                "func": _sequencer_function(block_specs, len(routes)),
                "outputs": len(routes) + 1,
                "timeout": 0,
                "noerr": 0,
                "initialize": "",
                "finalize": "",
                "libs": [],
                "x": 410,
                "y": 150,
                "wires": [
                    [read_ids[index], watchdog_id] for index in range(len(routes))
                ]
                + [[plan_status_debug_id]],
            },
        ]
    )
    for route_index, route in enumerate(routes):
        nodes.append(
            {
                "id": read_ids[route_index],
                "type": "modbus-flex-getter",
                "z": flow_id,
                "name": f"Read route: {route}",
                "showStatusActivities": True,
                "showErrors": True,
                "showWarnings": True,
                "server": clients[route],
                "useIOFile": False,
                "ioFile": "",
                "useIOForPayload": False,
                "emptyMsgOnFail": True,
                "keepMsgProperties": True,
                "x": 650,
                "y": 120 + route_index * 45,
                "wires": [[response_gate_id], [capture_id, error_debug_id]],
            }
        )

    nodes.extend(
        [
            {
                "id": response_gate_id,
                "type": "function",
                "z": flow_id,
                "name": "Accept complete read",
                "func": _response_gate_function(),
                "outputs": 2,
                "timeout": 0,
                "noerr": 0,
                "initialize": "",
                "finalize": "",
                "libs": [],
                "x": 890,
                "y": 150,
                "wires": [[decode_id, watchdog_reset_id], [capture_id, error_debug_id]],
            },
            {
                "id": decode_id,
                "type": "function",
                "z": flow_id,
                "name": "Derive points",
                "func": _derive_function(),
                "outputs": 1,
                "timeout": 0,
                "noerr": 0,
                "initialize": "",
                "finalize": "",
                "libs": [],
                "x": 1110,
                "y": 135,
                "wires": [[capture_id]],
            },
            {
                "id": capture_id,
                "type": "function",
                "z": flow_id,
                "name": "Build capture/v1",
                "func": _capture_function(
                    map_digest,
                    plan_digest,
                    [block["block_id"] for block in block_specs],
                ),
                "outputs": 2,
                "timeout": 0,
                "noerr": 0,
                "initialize": "",
                "finalize": "",
                "libs": [],
                "x": 1320,
                "y": 150,
                "wires": [[capture_file_id], [sequencer_id]],
            },
            {
                "id": capture_file_id,
                "type": "file",
                "z": flow_id,
                "name": "Write capture.json",
                "filename": "filename",
                "filenameType": "msg",
                "appendNewline": False,
                "createDir": True,
                "overwriteFile": "true",
                "encoding": "none",
                "x": 1540,
                "y": 135,
                "wires": [[]],
            },
            {
                "id": watchdog_reset_id,
                "type": "function",
                "z": flow_id,
                "name": "Reset watchdog",
                "func": "msg.reset = true;\nreturn msg;",
                "outputs": 1,
                "timeout": 0,
                "noerr": 0,
                "initialize": "",
                "finalize": "",
                "libs": [],
                "x": 1120,
                "y": 190,
                "wires": [[watchdog_id]],
            },
            {
                "id": watchdog_id,
                "type": "trigger",
                "z": flow_id,
                "name": "Read watchdog",
                "op1": "",
                "op2": stable_json({"state": "timeout"}, pretty=False),
                "op1type": "nul",
                "op2type": "json",
                "duration": "${MODBUS_WATCHDOG_MS}",
                "extend": True,
                "overrideDelay": False,
                "units": "ms",
                "reset": "",
                "bytopic": "all",
                "topic": "topic",
                "outputs": 1,
                "x": 900,
                "y": 230,
                "wires": [[capture_id, watchdog_debug_id]],
            },
        ]
    )

    status_id = _node_id(seed, "status")
    queue_id = _node_id(seed, "queue-signal")
    queue_debug_id = _node_id(seed, "queue-debug")
    catch_id = _node_id(seed, "catch")
    nodes.extend(
        [
            {
                "id": status_id,
                "type": "status",
                "z": flow_id,
                "name": "Read status",
                "scope": read_ids,
                "x": 150,
                "y": 40,
                "wires": [[queue_id]],
            },
            {
                "id": queue_id,
                "type": "function",
                "z": flow_id,
                "name": "Queue status signal",
                "func": (
                    "const status = msg.status || {};\n"
                    "msg.topic = 'modbus/queue-status';\n"
                    "msg.payload = {\n"
                    "  source_id: status.source ? status.source.id : null,\n"
                    "  fill: status.fill || null,\n"
                    "  shape: status.shape || null,\n"
                    "  text: status.text || null\n"
                    "};\n"
                    "return msg;"
                ),
                "outputs": 1,
                "timeout": 0,
                "noerr": 0,
                "initialize": "",
                "finalize": "",
                "libs": [],
                "x": 390,
                "y": 40,
                "wires": [[queue_debug_id]],
            },
            {
                "id": catch_id,
                "type": "catch",
                "z": flow_id,
                "name": "Read errors",
                "scope": read_ids,
                "uncaught": False,
                "x": 140,
                "y": 75,
                "wires": [[error_debug_id]],
            },
            {
                "id": error_debug_id,
                "type": "debug",
                "z": flow_id,
                "name": "Modbus read errors",
                "active": True,
                "tosidebar": True,
                "console": False,
                "tostatus": False,
                "complete": "true",
                "targetType": "full",
                "x": 680,
                "y": 40,
                "wires": [],
            },
            {
                "id": plan_status_debug_id,
                "type": "debug",
                "z": flow_id,
                "name": "Read plan status",
                "active": True,
                "tosidebar": True,
                "console": False,
                "tostatus": False,
                "complete": "payload",
                "targetType": "msg",
                "x": 670,
                "y": 270,
                "wires": [],
            },
            {
                "id": queue_debug_id,
                "type": "debug",
                "z": flow_id,
                "name": "Queue signals",
                "active": False,
                "tosidebar": True,
                "console": False,
                "tostatus": False,
                "complete": "payload",
                "targetType": "msg",
                "x": 650,
                "y": 75,
                "wires": [],
            },
            {
                "id": watchdog_debug_id,
                "type": "debug",
                "z": flow_id,
                "name": "Read watchdog alerts",
                "active": True,
                "tosidebar": True,
                "console": False,
                "tostatus": False,
                "complete": "payload",
                "targetType": "msg",
                "x": 690,
                "y": 110,
                "wires": [],
            },
        ]
    )

    node_ids = [node["id"] for node in nodes]
    if len(node_ids) != len(set(node_ids)):
        findings.append(
            Finding(
                "error",
                "NODE_ID_COLLISION",
                "Deterministic Node-RED node IDs collided.",
            )
        )
        return held_result(
            TARGET,
            canonical_map,
            read_plan,
            mode=mode,
            adapter_version=ADAPTER_VERSION,
            findings=findings,
        )

    environment = []
    for route in routes:
        prefix = route_env[route]
        environment.extend([f"{prefix}_HOST", f"{prefix}_PORT"])
    environment.extend(["MODBUS_WATCHDOG_MS", "MODBUS_CAPTURE_PATH"])
    manifest = target_manifest(
        target=TARGET,
        profile=None,
        mode=mode,
        adapter_version=ADAPTER_VERSION,
        canonical_map=canonical_map,
        read_plan=read_plan,
        findings=findings,
        extra={
            "disabled_by_default": True,
            "required_node_module": "node-red-contrib-modbus",
            "environment": environment,
            "physical_read_nodes": len(read_ids),
            "read_block_ids": [block_id(block, index) for index, block in blocks],
            "read_node_type": "modbus-flex-getter",
            "trigger_type": "sequenced-manual-plan",
            "trigger_nodes": 1,
            "sequencing": "response-driven",
            "max_in_flight": 1,
            "capture_contract": "capture/v1",
            "scheduled_polling": False,
            **(
                {
                    "probe_trigger_type": "sequenced-manual-plan",
                    "probe_trigger_nodes": 1,
                    "probe_polling": False,
                    "probe_byte_order_candidates": list(
                        _PROBE_BYTE_ORDER_LAYOUTS
                    ),
                    "probe_candidate_interpretations": list(
                        _PROBE_32_BIT_INTERPRETATIONS
                    ),
                    "probe_candidate_source": "one-read-immutable-raw-words",
                }
                if mode == "probe"
                else {}
            ),
        },
    )
    artifacts = (
        Artifact.text(
            "node-red/flow.json",
            "application/json",
            stable_json(nodes),
            "node-red-flow",
        ),
        Artifact.text(
            "node-red/manifest.json",
            "application/json",
            stable_json(manifest),
            "target-manifest",
        ),
        Artifact.text(
            "node-red/README.md",
            "text/markdown",
            _readme(mode=mode, environment=environment),
            "operator-instructions",
        ),
    )
    return ExportResult(
        target=TARGET,
        status="generated",
        mode=mode,
        map_hash=map_digest,
        read_plan_hash=plan_digest,
        adapter_version=ADAPTER_VERSION,
        findings=tuple(findings),
        artifacts=artifacts,
    )


def _sequencer_function(block_specs: list[dict[str, Any]], route_count: int) -> str:
    return (
        f"const blocks = {stable_json(block_specs, pretty=False)};\n"
        f"const routeCount = {route_count};\n"
        "const statusIndex = routeCount;\n"
        "const output = (index, value) => {\n"
        "  const values = Array(routeCount + 1).fill(null);\n"
        "  values[index] = value;\n"
        "  return values;\n"
        "};\n"
        "const next = () => {\n"
        "  const queue = flow.get('modbusSkillsQueue') || [];\n"
        "  if (queue.length === 0) {\n"
        "    flow.set('modbusSkillsRunning', false);\n"
        "    return output(statusIndex, {payload: {state: 'complete', request_count: blocks.length}});\n"
        "  }\n"
        "  const block = queue.shift();\n"
        "  flow.set('modbusSkillsQueue', queue);\n"
        "  const request = {\n"
        "    block_id: block.block_id, route_id: block.route_id, unit_id: block.unit_id,\n"
        "    area: block.area, function_code: block.function_code,\n"
        "    start_offset: block.start_offset, quantity: block.quantity,\n"
        "    mode: block.mode, point_specs: block.point_specs, started_at_ms: Date.now()\n"
        "  };\n"
        "  const requestMsg = {\n"
        "    topic: block.block_id, modbusSkillsRequest: request,\n"
        "    payload: {fc: block.function_code, unitid: block.unit_id, address: block.start_offset, quantity: block.quantity}\n"
        "  };\n"
        "  return output(block.route_index, requestMsg);\n"
        "};\n"
        "if (msg && msg.payload && msg.payload.action === 'start') {\n"
        "  if (flow.get('modbusSkillsRunning')) {\n"
        "    return output(statusIndex, {payload: {state: 'already-running'}});\n"
        "  }\n"
        "  flow.set('modbusSkillsRunning', true);\n"
        "  flow.set('modbusSkillsQueue', blocks.slice());\n"
        "  flow.set('modbusSkillsCapture', []);\n"
        "  flow.set('modbusSkillsRunId', `run-${Date.now()}`);\n"
        "  return next();\n"
        "}\n"
        "if (msg && msg.modbusSkillsContinue === true) return next();\n"
        "return output(statusIndex, {payload: {state: 'ignored-message'}});"
    )


def _derive_function() -> str:
    return (
        "const block = msg.modbusSkillsRequest || {};\n"
        "const pointSpecs = Array.isArray(block.point_specs) ? block.point_specs : [];\n"
        "const byteLayouts32 = Object.freeze({\n"
        "  ABCD: Object.freeze([0, 1, 2, 3]),\n"
        "  BADC: Object.freeze([1, 0, 3, 2]),\n"
        "  CDAB: Object.freeze([2, 3, 0, 1]),\n"
        "  DCBA: Object.freeze([3, 2, 1, 0])\n"
        "});\n"
        "const decode32 = (sourceBytes, layout) => {\n"
        "  const order = byteLayouts32[layout];\n"
        "  const buffer = Buffer.from(order.map((index) => sourceBytes[index]));\n"
        "  const float32 = buffer.readFloatBE(0);\n"
        "  return Object.freeze({\n"
        "    bytes: Object.freeze(Array.from(buffer.values())),\n"
        "    uint32: buffer.readUInt32BE(0),\n"
        "    int32: buffer.readInt32BE(0),\n"
        "    float32: Number.isFinite(float32) ? float32 : null\n"
        "  });\n"
        "};\n"
        "const candidate = Array.isArray(msg.payload)\n"
        "  ? msg.payload\n"
        "  : (msg.payload && Array.isArray(msg.payload.data) ? msg.payload.data : []);\n"
        "const rawValues = Object.freeze(candidate.slice());\n"
        "msg.modbusSkills = { block, raw_values: rawValues };\n"
        "msg.payload = pointSpecs.map((spec) => {\n"
        "  const offset = Number.isInteger(spec.relative_offset) ? spec.relative_offset : 0;\n"
        "  const width = Number.isInteger(spec.word_count) ? spec.word_count : 1;\n"
        "  const pointRawValues = Object.freeze(rawValues.slice(offset, offset + width));\n"
        "  const derived = Object.assign({}, spec, { raw_values: pointRawValues });\n"
        "  if (block.mode === 'probe' && width === 2 && pointRawValues.length === 2) {\n"
        "    const firstWord = Number(pointRawValues[0]) & 0xffff;\n"
        "    const secondWord = Number(pointRawValues[1]) & 0xffff;\n"
        "    const sourceBytes = Object.freeze([\n"
        "      (firstWord >>> 8) & 0xff, firstWord & 0xff,\n"
        "      (secondWord >>> 8) & 0xff, secondWord & 0xff\n"
        "    ]);\n"
        "    derived.byte_order_candidates = Object.freeze(Object.fromEntries(\n"
        "      Object.keys(byteLayouts32).map((layout) => [layout, decode32(sourceBytes, layout)])\n"
        "    ));\n"
        "  }\n"
        "  return derived;\n"
        "});\n"
        "return msg;"
    )


def _capture_function(
    map_digest: str,
    plan_digest: str,
    block_ids: list[str],
) -> str:
    return (
        f"const mapHash = {stable_json(map_digest, pretty=False)};\n"
        f"const planHash = {stable_json(plan_digest, pretty=False)};\n"
        f"const expectedBlockIds = {stable_json(block_ids, pretty=False)};\n"
        "const request = msg.modbusSkillsRequest || {};\n"
        "const runId = flow.get('modbusSkillsRunId');\n"
        "const requestId = `${runId}:${request.block_id}`;\n"
        "const timestamp = new Date().toISOString();\n"
        "const elapsed = Number.isFinite(request.started_at_ms) ? Date.now() - request.started_at_ms : null;\n"
        "const derived = Array.isArray(msg.payload) ? msg.payload : [];\n"
        "const successful = derived.length > 0 && !msg.error && !msg.modbusError && !msg.modbusSkillsReadError;\n"
        "const points = Array.isArray(request.point_specs) ? request.point_specs : [];\n"
        "const samples = successful ? derived.map((point) => ({\n"
        "  sample_id: `${requestId}:${point.point_id}`, request_id: requestId,\n"
        "  point_id: point.point_id, block_id: request.block_id, route_id: request.route_id,\n"
        "  unit_id: request.unit_id, area: request.area,\n"
        "  protocol_offset: request.start_offset + (Number.isInteger(point.relative_offset) ? point.relative_offset : 0),\n"
        "  timestamp, response_time_ms: elapsed, success: true, raw_words: point.raw_values || [],\n"
        "  derived_values: point\n"
        "})) : points.map((point) => ({\n"
        "  sample_id: `${requestId}:${point.point_id}:error`, request_id: requestId,\n"
        "  point_id: point.point_id, block_id: request.block_id, route_id: request.route_id,\n"
        "  unit_id: request.unit_id, area: request.area,\n"
        "  protocol_offset: request.start_offset + (Number.isInteger(point.relative_offset) ? point.relative_offset : 0),\n"
        "  timestamp, response_time_ms: elapsed, success: false, raw_words: [],\n"
        "  error: (msg.modbusSkillsReadError && msg.modbusSkillsReadError.reason) ||\n"
        "    (msg.payload && msg.payload.state) || (msg.error && msg.error.message) || 'read-failed'\n"
        "}));\n"
        "const existing = flow.get('modbusSkillsCapture') || [];\n"
        "existing.push(...samples);\n"
        "const combined = existing;\n"
        "flow.set('modbusSkillsCapture', combined);\n"
        "const capture = {\n"
        "  schema_version: \"capture/v1\", capture_id: runId,\n"
        "  canonical_map_hash: mapHash, read_plan_hash: planHash,\n"
        "  expected_request_ids: expectedBlockIds.map((id) => `${runId}:${id}`), samples: combined\n"
        "};\n"
        "const fileMsg = {\n"
        "  filename: env.get('MODBUS_CAPTURE_PATH') || 'modbus-capture.json',\n"
        "  payload: JSON.stringify(capture, null, 2)\n"
        "};\n"
        "return [fileMsg, {modbusSkillsContinue: true, payload: {action: 'next'}}];"
    )


def _response_gate_function() -> str:
    """Accept only a complete, successful read response.

    The success output feeds both derivation and the watchdog reset. The error
    output feeds only the error debug node, so an empty or failed response
    cannot look like a completed read.
    """

    return (
        "const request = msg.modbusSkillsRequest || {};\n"
        "const expected = {block_id: request.block_id, expected_quantity: request.quantity};\n"
        "const payloadData = msg.payload && Array.isArray(msg.payload.data)\n"
        "  ? msg.payload.data\n"
        "  : null;\n"
        "const values = Array.isArray(msg.payload) ? msg.payload : payloadData;\n"
        "const explicitFailure = Boolean(\n"
        "  msg.error || msg.modbusError ||\n"
        "  (msg.payload && !Array.isArray(msg.payload) && msg.payload.error)\n"
        ");\n"
        "const complete = Array.isArray(values) &&\n"
        "  values.length === expected.expected_quantity;\n"
        "if (explicitFailure || !complete) {\n"
        "  msg.modbusSkillsReadError = {\n"
        "    state: 'invalid-read-response',\n"
        "    block_id: expected.block_id,\n"
        "    expected_quantity: expected.expected_quantity,\n"
        "    received_quantity: Array.isArray(values) ? values.length : 0,\n"
        "    reason: explicitFailure ? 'read-failed' : 'read-wrong-length'\n"
        "  };\n"
        "  return [null, msg];\n"
        "}\n"
        "return [msg, null];"
    )


def _node_id(seed: str, role: str) -> str:
    return hashlib.sha256(f"{seed}:{role}".encode("utf-8")).hexdigest()[:16]


def _readme(*, mode: str, environment: list[str]) -> str:
    environment_lines = "\n".join(f"- `{name}`" for name in environment)
    run_instructions = (
        "After you enable the tab, click `Run bounded read plan` once. The flow "
        "sends the next request only after the current request returns or times "
        "out. It has no scheduled polling and does not run at deploy."
    )
    return f"""# Node-RED {mode.title()} Flow

This target contains one read path for each compiled read block. It does not
contain Modbus write nodes or network discovery logic.

The flow tab is disabled by default. Review all settings before you enable it.

## Requirements

- Node-RED.
- `node-red-contrib-modbus`.
- The environment variables below.

{environment_lines}

Set each port to a decimal TCP port. {run_instructions} Import `flow.json`,
review it, deploy it while it is disabled, and then enable the tab only when
the endpoint is safe for one bounded read.

Set `MODBUS_CAPTURE_PATH` to the local path for `capture.json`. The flow
rewrites that file after every response so it always contains a complete
`capture/v1` document. The flow uses one shared reader per route and keeps one
request in flight.

The derive nodes keep an immutable copy of the raw values. They also attach
point datatype, byte-order, scaling, and engineering-unit metadata. For each
two-register point, probe mode derives `ABCD`, `BADC`, `CDAB`, and `DCBA`
candidates from the same raw words. Each candidate includes unsigned integer,
signed integer, and float interpretations. The flow does not choose a winner.
"""
